name: MineSweeper
version: 0.1.0
main: edu.shch.mine.MineSweeperPlugin
bootstrapper: edu.shch.mine.MineSweeperPluginBootstrap
load: STARTUP
description: Minesweeper in Minecraft
author: Me
website: https://c0mpl3x.one
api-version: '1.21.11'